version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: node
        environment:
            - NODE_ENV=DEVELOPMENT
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        ports:
            - 5173:5173
        working_dir: /usr/src/app
        tty: true
volumes:
    node_modules:
